# NOTE: Before deploying to a production environment, please review the documentation -> https://aka.ms/self-hosted-gateway-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arc-deployed-gateway-env
data:
  config.service.endpoint: "https://contoso.management.azure-api.net/subscriptions/c6a33fd3-e442-48a4-b82d-bcc4ad8a71d7/resourceGroups/Build2020/providers/Microsoft.ApiManagement/service/contoso?api-version=2019-12-01"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-deployed-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arc-deployed-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: arc-deployed-gateway
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: arc-deployed-gateway
        image: mcr.microsoft.com/azure-api-management/gateway:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: arc-deployed-gateway-token
              key: value
        envFrom:
        - configMapRef:
            name: arc-deployed-gateway-env
---
apiVersion: v1
kind: Service
metadata:
  name: arc-deployed-gateway
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: arc-deployed-gateway
